/**
 * ContentBloom - SEO Article Generator
 * 
 * Generates high-quality SEO content for e-commerce stores:
 * - Product-focused articles
 * - Buying guides
 * - How-to content
 * - Comparison articles
 */

export interface ArticleRequest {
  storeName: string;
  storeUrl: string;
  niche: string;
  products: string[];
  targetKeyword: string;
  articleType: 'guide' | 'howto' | 'comparison' | 'listicle' | 'story';
  language: 'en' | 'es' | 'de' | 'fr';
  wordCount: number;
}

export interface GeneratedArticle {
  title: string;
  metaDescription: string;
  content: string;
  targetKeyword: string;
  secondaryKeywords: string[];
  suggestedImages: string[];
  internalLinks: string[];
  wordCount: number;
  readingTime: number;
}

/**
 * Generate content strategy for a store
 */
export function generateContentStrategy(
  storeName: string,
  niche: string,
  products: string[]
): string[] {
  // Article ideas based on niche and products
  const templates = [
    `The Ultimate Guide to Choosing ${niche} Products in 2026`,
    `${products[0]} vs ${products[1]}: Which is Right for You?`,
    `10 Ways to Get the Most Out of Your ${niche}`,
    `How to Care for Your ${niche} Products`,
    `Why Quality ${niche} Makes All the Difference`,
    `${niche} Trends to Watch in 2026`,
    `A Beginner's Guide to ${niche}`,
    `Common ${niche} Mistakes and How to Avoid Them`,
    `The History of ${niche}: From Past to Present`,
    `Expert Tips: Getting Started with ${niche}`,
  ];
  
  return templates;
}

/**
 * Generate article prompt for Claude
 */
export function generateArticlePrompt(request: ArticleRequest): string {
  const languageInstructions = {
    en: 'Write in American English.',
    es: 'Write in Spanish (Spain).',
    de: 'Write in German.',
    fr: 'Write in French.'
  };
  
  const typeInstructions = {
    guide: 'This should be a comprehensive buying guide that helps readers make informed decisions.',
    howto: 'This should be a step-by-step tutorial that walks readers through a process.',
    comparison: 'This should compare different options objectively, highlighting pros and cons.',
    listicle: 'This should be an engaging list format with clear sections.',
    story: 'This should tell a compelling story that connects emotionally with readers.'
  };
  
  return `You are an expert SEO copywriter for e-commerce stores.

Write a ${request.wordCount}+ word article for ${request.storeName} (${request.storeUrl}), an online store in the ${request.niche} space.

**Article Details:**
- Type: ${request.articleType}
- Target keyword: "${request.targetKeyword}"
- Products to mention: ${request.products.join(', ')}

**Instructions:**
${typeInstructions[request.articleType]}
${languageInstructions[request.language]}

**SEO Requirements:**
- Include the target keyword in the title, first paragraph, and 2-3 times naturally throughout
- Use H2 and H3 headings with keyword variations
- Write a compelling meta description (150-160 characters)
- Include a clear call-to-action linking to the store's products

**Tone:**
- Friendly and conversational, not salesy
- Expert but accessible
- Focus on helping the reader, not just selling

**Structure:**
1. Hook/Introduction (capture attention)
2. Main content (valuable information)
3. Product mentions (natural, not forced)
4. Conclusion with CTA

**Output Format:**
Return as JSON:
{
  "title": "SEO-optimized title with keyword",
  "metaDescription": "150-160 char description",
  "content": "Full article in markdown format",
  "secondaryKeywords": ["keyword1", "keyword2", "keyword3"],
  "suggestedImages": ["Description of image 1", "Description of image 2"],
  "internalLinks": ["Suggested anchor text for product link 1"]
}`;
}

/**
 * Format article for delivery (PDF-ready markdown)
 */
export function formatArticleForDelivery(article: GeneratedArticle, storeName: string): string {
  return `# ${article.title}

**Store:** ${storeName}
**Target Keyword:** ${article.targetKeyword}
**Word Count:** ${article.wordCount} words
**Reading Time:** ${article.readingTime} minutes

---

## Meta Description
> ${article.metaDescription}

---

## Article Content

${article.content}

---

## SEO Checklist
- [ ] Add meta description to Shopify SEO settings
- [ ] Add target keyword to URL slug
- [ ] Include alt text on all images
- [ ] Add internal links to product pages

## Suggested Images
${article.suggestedImages.map((img, i) => `${i + 1}. ${img}`).join('\n')}

## Secondary Keywords to Include
${article.secondaryKeywords.map(kw => `- ${kw}`).join('\n')}

---

*Generated by ContentBloom for ${storeName}*
`;
}

/**
 * Generate demo package for a store
 */
export async function generateDemoPackage(
  storeName: string,
  storeUrl: string,
  niche: string,
  products: string[],
  language: 'en' | 'es' | 'de' | 'fr' = 'en'
): Promise<{
  articles: GeneratedArticle[];
  strategy: string[];
}> {
  // Generate content strategy
  const strategy = generateContentStrategy(storeName, niche, products);
  
  // Generate 2 demo articles
  const articleRequests: ArticleRequest[] = [
    {
      storeName,
      storeUrl,
      niche,
      products,
      targetKeyword: `best ${niche} guide`,
      articleType: 'guide',
      language,
      wordCount: 1500
    },
    {
      storeName,
      storeUrl,
      niche,
      products,
      targetKeyword: `how to choose ${niche}`,
      articleType: 'howto',
      language,
      wordCount: 1500
    }
  ];
  
  // In production, this would call Claude API
  // For now, return structure for OSCR to fill
  const articles: GeneratedArticle[] = articleRequests.map(req => ({
    title: `[GENERATE: ${req.articleType} about ${req.targetKeyword}]`,
    metaDescription: '[GENERATE: 150-160 char meta description]',
    content: generateArticlePrompt(req),
    targetKeyword: req.targetKeyword,
    secondaryKeywords: [],
    suggestedImages: [],
    internalLinks: [],
    wordCount: req.wordCount,
    readingTime: Math.ceil(req.wordCount / 200)
  }));
  
  return { articles, strategy };
}
